name: rfm_segmentation_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - mlflow
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - hdbscan
      - joblib
      - openpyxl
      - scipy


